Removed feature of gui, codecosmetic

diff --git a/domotemplate b/domotemplate
--- a/domotemplate
+++ b/domotemplate
@@ -10,46 +10,34 @@ script_name="domotemplate"
 script_version="v0.2.1"
 script_tools="echo date clear test"
 
+# From here on warn about empty variables
+set -u
+
 # Definition of colors
-NOCOLOR=0
-for paraval in "$@"; do
-  if [ "$paraval" = "-n" ] || [ "$paraval" = "--nocolor" ]; then
-    NOCOLOR=1
-  fi
-done
-if [ "$NOCOLOR" = "1" ]; then
-  color_off=
+color_off="\033[0m"
+color_black="\033[0;30m"
+color_red="\033[0;31m"
+color_green="\033[0;32m"
+color_yellow="\033[0;33m"
+color_blue="\033[0;34m"
+color_purple="\033[0;35m"
+color_cyan="\033[0;36m"
+color_white="\033[0;37m"
+color_bold_black="\033[1;30m"
+color_bold_red="\033[1;31m"
+color_bold_green="\033[1;32m"
+color_bold_yellow="\033[1;33m"
+color_bold_blue="\033[1;34m"
+color_bold_purple="\033[1;35m"
+color_bold_cyan="\033[1;36m"
+color_bold_white="\033[1;37m"
 
-  color_header=
-  color_time=
-  color_section=
-  color_mark=
-  color_error=
-else
-  color_off="\033[0m"
-  color_black="\033[0;30m"
-  color_red="\033[0;31m"
-  color_green="\033[0;32m"
-  color_yellow="\033[0;33m"
-  color_blue="\033[0;34m"
-  color_purple="\033[0;35m"
-  color_cyan="\033[0;36m"
-  color_white="\033[0;37m"
-  color_bold_black="\033[1;30m"
-  color_bold_red="\033[1;31m"
-  color_bold_green="\033[1;32m"
-  color_bold_yellow="\033[1;33m"
-  color_bold_blue="\033[1;34m"
-  color_bold_purple="\033[1;35m"
-  color_bold_cyan="\033[1;36m"
-  color_bold_white="\033[1;37m"
-
-  color_header=$color_bold_red
-  color_time=$color_bold_purple
-  color_section=$color_bold_yellow
-  color_mark=$color_bold_green
-  color_error=$color_bold_red
-fi
+# Definition of used theme colors
+color_header=$color_bold_red
+color_time=$color_bold_purple
+color_section=$color_bold_yellow
+color_mark=$color_bold_green
+color_error=$color_bold_red
 
 # Function to end script with exit code and wait for ENTER key to close window (if wait on exit requested)
 function ScriptExit()
@@ -70,38 +58,6 @@ function ScriptExit()
   fi
 }
 
-# Start terminal as GUI if requested
-if [ "$SCRIPT_STARTED_IN_GUI" != 1 ]; then
-  for paraval in "$@"; do
-    if [ "$paraval" = "-g" ] || [ "$paraval" = "--gui" ]; then
-      gnome-terminal --title $script_name" "$script_version -- /usr/bin/env "SCRIPT_STARTED_IN_GUI=1" "$0" "$@"
-      exit
-    fi
-  done
-fi
-
-# Handle Terminal Environment
-echo -en "$color_off""Running $color_mark$script_name$color_off version $color_mark$script_version$color_off"
-if [ "$SCRIPT_STARTED_IN_GUI" = 1 ]; then
-  echo -en " in $color_mark""GUI$color_off"
-else
-  SCRIPT_STARTED_IN_GUI=0
-  set -u # From her on warn about empty variables
-  echo -en " in $color_mark""Terminal$color_off"
-fi
-echo -en " as user $color_mark$(id -un)$color_off"
-if   [ $# -eq 1 ]; then
-  echo -e " with parameter $color_mark\"$@\"$color_off"
-elif [ $# -gt 1 ]; then
-  echo -en " with $color_mark$#$color_off parameters$color_mark"
-  for x in "$@"; do
-    echo -en " \"$x\""
-  done
-  echo -e "$color_off"
-else
-  echo -e " with $color_mark""no$color_off parameters"
-fi
-
 # Check Parameters
 WAIT_ON_EXIT=0
 while [ $# -gt 0 ]; do # Parameter given?
@@ -115,7 +71,6 @@ while [ $# -gt 0 ]; do # Parameter given?
     echo
     echo "Options"
     echo "-d, --debug     Print all executed commands"
-    echo "-g, --gui      Start script in X gui window"
     echo "-h, --help      Print this help"
     echo "-n, --nocolor   Don't color output"
     echo "-w, --wait      Wait on exit"
@@ -125,25 +80,18 @@ while [ $# -gt 0 ]; do # Parameter given?
     echo " 1  if ERROR"
     ScriptExit 0
   elif [ "$1" = "-n" ] || [ "$1" = "--nocolor" ]; then
-    # Do nothing here, this is handled above
+    color_off=
+    color_header=
+    color_time=
+    color_section=
+    color_mark=
+    color_error=
     shift
   elif [ "$1" = "-w" ] || [ "$1" = "--wait" ]; then
     WAIT_ON_EXIT=1
     shift
-  elif [ "$1" = "-g" ] || [ "$1" = "--gui" ]; then
-    # Do nothing here, starting of gui is handled above
-    shift
   else
     echo -e "Unknown parameter $color_mark$1$color_off"
-    ScriptExit 1
-  fi
-done
-
-# Check for needed tools
-for x in $script_tools; do # Run through tool list
-  which $x > /dev/null
-  if [ $? -ne 0 ]; then
-    echo -e "Tool $color_mark$x$color_off is missing!"
     ScriptExit 1
   fi
 done
@@ -157,6 +105,30 @@ echo "| (_| | (_) | | | | | | (_) | |  __/ | | | | | |_) | | (_| | ||  __/"
 echo " \__,_|\___/|_| |_| |_|\___/|_|\___|_| |_| |_| .__/|_|\__,_|\__\___|"
 echo "                                             |_|                    "
 echo -e "$color_header$script_name $script_version$color_off"
+echo
+
+# Check for needed tools
+for x in $script_tools; do # Run through tool list
+  which $x > /dev/null
+  if [ $? -ne 0 ]; then
+    echo -e "Tool $color_mark$x$color_off is missing!"
+    ScriptExit 1
+  fi
+done
+
+# Show Terminal Environment and script startup info
+echo -en "$color_off""Running as user $color_mark$(id -un)$color_off"
+if   [ $# -eq 1 ]; then
+  echo -e " with parameter $color_mark\"$@\"$color_off"
+elif [ $# -gt 1 ]; then
+  echo -en " with $color_mark$#$color_off parameters$color_mark"
+  for x in "$@"; do
+    echo -en " \"$x\""
+  done
+  echo -e "$color_off"
+else
+  echo -e " with $color_mark""no$color_off parameters"
+fi
 echo
 
 # Start time measurement
